{% set name = "youtube_dl" %}
{% set version = "2021.12.17" %}

package:
  name: youtube-dl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/y/youtube_dl/youtube_dl-{{ version }}.tar.gz
  sha256: bc59e86c5d15d887ac590454511f08ce2c47698d5a82c27bfe27b5d814bbaed2

build:
  number: 1
  noarch: python
  entry_points:
    - youtube-dl = youtube_dl:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - youtube-dl --help
    - pip check
  imports:
    - youtube_dl
    - youtube_dl.downloader
    - youtube_dl.extractor
    - youtube_dl.postprocessor

about:
  home: http://rg3.github.io/youtube-dl/
  license: LicenseRef-Public-Domain
  license_family: OTHER
  license_url: http://unlicense.org
  license_file: LICENSE
  summary: YouTube video downloader
  description: |
    Command-line program to download videos from YouTube.com and other video sites
  doc_url: https://github.com/rg3/youtube-dl/blob/master/README.md#readme
  dev_url: https://github.com/rg3/youtube-dl

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
